// ---- PISTON v2: one level deeper ----
// Every step of the ideal test-drive journey with its source, screen, entry and exit conditions,
// per track (booked hub TD, walk-in hub TD, video TD). Mock people and numbers are examples only.
//
// A field can be a plain value, or an object keyed by track: { booked, walkin, vtd, hub, all }.
// "hub" covers booked + walk-in. pick() resolves it for the active track.

const TRACKS = {
  booked: { key: "booked", label: "Booked hub TD", short: "Booked", who: "Fatima Al Suwaidi" },
  walkin: { key: "walkin", label: "Walk-in hub TD", short: "Walk-in", who: "Ahmed Saleh" },
  vtd:    { key: "vtd",    label: "Video TD", short: "VTD", who: "Khalid Al Jaberi" },
};

function pick(val, track) {
  if (val == null || typeof val !== "object" || Array.isArray(val)) return val;
  const keyed = ["all", "booked", "walkin", "vtd", "hub"].some(k => k in val);
  if (!keyed) return val;
  if (track in val) return val[track];
  if (track !== "vtd" && "hub" in val) return val.hub;
  return val.all;
}

// ---------------------------------------------------------------- flow level
const FLOWS = {
  booked: {
    source: ["Consumer app (CDP)", "Call centre", "Chatbot"],
    entry: ["Hub TD booked for today (ORDER BOOKED)", "Customer arrives at the booked hub"],
    exit: [
      ["good", "TOKEN PAID", "handed to the delivery journey"],
      ["warn", "FOLLOW-UP SCHEDULED", "date agreed, shortlist shared"],
      ["warn", "NEW TD BOOKED", "another car, restarts at Plan"],
      ["bad", "DROPPED", "reason recorded"],
      ["warn", "No-show", "back to nurture (P4)"],
    ],
  },
  walkin: {
    source: ["Drive-by", "Referral", "Social or search ad", "Radio and outdoor"],
    entry: ["Customer at the hub without a booking", "A valid licence is needed to drive; car finding works without one"],
    exit: [
      ["good", "TOKEN PAID", "handed to the delivery journey"],
      ["warn", "FOLLOW-UP SCHEDULED", "includes browse-only visits"],
      ["warn", "NEW TD BOOKED", "another day or another car"],
      ["bad", "DROPPED", "reason recorded"],
    ],
  },
  vtd: {
    source: ["Consumer app (CDP)", "Call centre", "Chatbot"],
    entry: ["VTD booked (link sent, operator allocated)", "Customer joins the video link within 15 min of the slot"],
    exit: [
      ["good", "TOKEN PAID", "by payment link"],
      ["warn", "NEW TD BOOKED", "a hub TD after the video"],
      ["warn", "FOLLOW-UP SCHEDULED", "date agreed"],
      ["bad", "DROPPED", "reason recorded"],
    ],
  },
};

// ---------------------------------------------------------------- phase level
const PHASES = [
  { id: "P", name: "Plan", when: "Before arrival", owner: "Call centre, consumer app, system",
    entry: "Customer shows TD intent", exit: { all: "Ready for the visit, or back to nurture" } },
  { id: "I", name: "Introduce", when: "First 3 minutes", owner: { hub: "Receptionist", vtd: "VTD operator" },
    entry: { hub: "Customer walks in", vtd: "Customer opens the video link" }, exit: "Arrival logged, customer welcomed" },
  { id: "S", name: "Sign-in", when: "Front desk", owner: { hub: "Receptionist", vtd: "VTD operator" },
    entry: "Customer welcomed", exit: { hub: "CHECKED IN and DA ASSIGNED. No TD consent here", vtd: "VTD CHECKED IN" } },
  { id: "T", name: "Tailor", when: { hub: "Handshake, then car finding", vtd: "Car finding over screen share" }, owner: { hub: "DA, from the handshake to the close", vtd: "VTD operator" },
    entry: { hub: "DA ASSIGNED", vtd: "VTD CHECKED IN" }, exit: { hub: "Cars confirmed for today and prep raised, or a follow-up", vtd: "Car confirmed for the video walkaround" } },
  { id: "O", name: "On the road", when: "At the car", owner: { hub: "DA", vtd: "VTD operator" },
    entry: { hub: "Cars confirmed, prep raised", vtd: "Car on camera" }, exit: { hub: "TD CONDUCTED for every car", vtd: "VTD CONDUCTED" } },
  { id: "N", name: "Next step", when: "No visit ends without one", owner: "DA, then RM",
    entry: "TD conducted, or a visit with no drive", exit: "TOKEN PAID, FOLLOW-UP SCHEDULED, NEW TD BOOKED or DROPPED" },
  { id: "M", name: "Oversight", when: "All day", owner: "Manager (DATL)",
    entry: "Manager role", exit: "Late steps caught and reassigned" },
];

// ---------------------------------------------------------------- step level
const STEPS = [
  // ============================== P · Plan
  { id: "P1", phase: "P", name: "Capture TD intent", tracks: ["booked", "vtd"],
    owner: "Call-centre agent, or the customer in the app", device: "desktop",
    purpose: "Turn a test-drive query into a booking-initiated order with a verified mobile.",
    source: { trigger: "Customer taps Book test drive in the app, calls in, or asks the chatbot",
      data: ["CDP profile and cars viewed", "Listing service: car is live at a hub", "User auth: mobile OTP"] },
    entry: ["Customer shows TD intent on a car or a body type", "Car is live and not reserved"],
    exits: [
      { when: "Mobile verified and car picked", to: "P2", state: "BOOKING INITIATED" },
      { when: "Not ready to pick a time", to: "P4" },
    ],
    state: "BOOKING INITIATED",
    screen: { name: "Lead detail &rsaquo; Book test drive", build: "extend",
      pattern: "Leads lead detail + a Book test drive side sheet (DYNAMIC_FORM)", route: "/leads/LD-55120?panel=book-td" },
  },
  { id: "P2", phase: "P", name: "Pick TD type and slot", tracks: ["booked", "vtd"],
    owner: "Call-centre agent, or the customer in the app", device: "desktop",
    purpose: "Choose a hub TD or a VTD and lock a slot that has DA and car capacity.",
    source: { trigger: "Agent continues from P1",
      data: ["Slot planner capacity (moving to the central Appointment Service)", "OMS order", "Notification engine: confirmation and video link"] },
    entry: ["BOOKING INITIATED", "Car can be driven at its hub, or shown on video"],
    exits: {
      booked: [{ when: "Hub slot confirmed", to: "P3", state: "ORDER BOOKED" }, { when: "No slot works for the customer", to: "P4" }],
      vtd: [{ when: "VTD slot confirmed, link sent, operator allocated", to: "P3", state: "VTD BOOKED" }, { when: "No slot works for the customer", to: "P4" }],
    },
    state: { booked: "ORDER BOOKED", vtd: "VTD BOOKED" },
    screen: { name: "Book test drive &rsaquo; Slot picker", build: "new",
      pattern: "Modal on the lead; reads slot capacity per hub and per DA", route: "/leads/LD-55120?panel=book-td&step=slot" },
  },
  { id: "P3", phase: "P", name: "Pre-arrival readiness", tracks: ["booked", "vtd"],
    owner: "System; receptionist watches the list", device: "desktop",
    purpose: "Customer, car and DA are all ready before the slot starts.",
    source: { trigger: "Order booked for the next 24 hours",
      data: ["Notification engine: reminders at T-24h and T-2h, with a DL upload link", "Docs: DL uploaded by the customer", "Prep tasks: car ready at a bay", "DA roster: pre-assigned by daily capacity"] },
    entry: [{ booked: "ORDER BOOKED", vtd: "VTD BOOKED" }, "Slot within the next 24 hours"],
    exits: {
      booked: [{ when: "Customer arrives at the hub", to: "I1" }, { when: "Customer reschedules", to: "P2" }, { when: "No-show 30 min after the slot", to: "P4" }],
      vtd: [{ when: "Customer opens the video link", to: "I1" }, { when: "Customer reschedules", to: "P2" }, { when: "Not joined 10 min after the slot", to: "P4" }],
    },
    state: null,
    screen: { name: "Test Drives &rsaquo; Upcoming", build: "extend",
      pattern: "Test Drives queue with readiness columns: DL, car prep, DA, reminder", route: "/test-drives?view=upcoming" },
  },
  { id: "P4", phase: "P", name: "Follow-up and nurture", tracks: ["booked", "vtd"], branch: true,
    owner: "Call-centre agent", device: "desktop",
    purpose: "Bring back customers who did not book or did not show.",
    source: { trigger: "Booking initiated with no slot after 24h, or a no-show",
      data: ["Leadverse Tasks: new TD follow-up persona", "Lead history and last call notes"] },
    entry: ["BOOKING INITIATED with no slot for 24h, or a no-show"],
    exits: [
      { when: "Customer rebooks", to: "P2" },
      { when: "No answer: try again, up to 3 attempts", to: "P4" },
      { when: "Not interested, or 3 attempts used", to: "N7", state: "DROPPED" },
    ],
    state: null,
    screen: { name: "Tasks &rsaquo; TD follow-up", build: "reuse",
      pattern: "Tasks &rarr; Lead &rarr; new persona b2c-lead-td-followup-by-cc", route: "/tasks?entity=lead&persona=td-follow-up" },
  },

  // ============================== I · Introduce
  { id: "I1", phase: "I", name: "Arrival", tracks: ["booked", "walkin", "vtd"],
    owner: { hub: "Receptionist", vtd: "VTD operator" }, device: { hub: "desktop", vtd: "video" },
    purpose: { hub: "Log the moment the customer arrives. It starts the clock and gives the DA a heads-up.", vtd: "Know the customer is on the call and start the clock." },
    source: {
      trigger: { booked: "Booked customer walks in", walkin: "Customer walks in without a booking", vtd: "Customer opens the video link" },
      data: { booked: ["Today's bookings (OMS + slot planner)"], walkin: ["Nothing yet. The visit is created here"], vtd: ["Video provider: join event"] },
    },
    entry: { booked: ["ORDER BOOKED for today at this hub"], walkin: ["None. Anyone can walk in"], vtd: ["VTD BOOKED", "Within 15 min of the slot"] },
    exits: {
      booked: [{ when: "Receptionist taps Mark arrived; the pre-assigned DA gets a heads-up", to: "I2" }],
      walkin: [{ when: "Receptionist starts a walk-in visit", to: "I2" }],
      vtd: [{ when: "Customer is in the call", to: "I2", state: "CUSTOMER JOINED CALL" }, { when: "Not joined 10 min after the slot", to: "P4" }],
    },
    state: { hub: null, vtd: "CUSTOMER JOINED CALL" },
    screen: { name: { hub: "Test Drives &rsaquo; Today", vtd: "VTD console &rsaquo; Waiting room" }, build: "extend",
      pattern: { hub: "Test Drives queue + Mark arrived row action + New walk-in button", vtd: "Video panel embedded with IFRAME_RENDERER" },
      route: { hub: "/test-drives?view=today", vtd: "/test-drives/BK-88190?stage=video" } },
    dap: { hub: "DAP has no arrival event. Its first timestamp is check-in.", vtd: "VTD work orders already move ASSIGNED, then CUSTOMER_JOINED_CALL." },
  },
  { id: "I2", phase: "I", name: "Welcome", tracks: ["booked", "walkin", "vtd"],
    owner: { hub: "Receptionist", vtd: "VTD operator" }, device: "none",
    purpose: { hub: "Greet, seat, offer tea, coffee or water, and explain today: check-in, car match, test drive.", vtd: "A warm on-camera welcome and a plan for the call." },
    source: { trigger: "Arrival logged in I1", data: ["None"] },
    entry: ["Arrival logged"],
    exits: [{ when: "Customer is settled and ready", to: "S1" }],
    state: null,
    screen: { name: "No screen, by design", build: "none",
      pattern: "A human moment. The only system touch is the arrival time from I1, which starts the arrival-to-handshake clock.", route: null },
    moments: {
      hub: ["Greet by name if booked, or welcome a walk-in", "Offer a seat and tea, coffee or water", "Explain today: check-in, a DA to find the right car, the test drive, then the next step"],
      vtd: ["Welcome on camera, check sound and video", "Explain the call: check-in, car finding on screen, a live walkaround, then the next step"],
    },
    target: { hub: "Check-in starts within 3 minutes of arrival", vtd: "Check-in starts within 2 minutes of joining" },
  },

  // ============================== S · Sign-in
  { id: "S1", phase: "S", name: "Check-in", tracks: ["booked", "walkin", "vtd"],
    owner: { hub: "Receptionist", vtd: "VTD operator" }, device: { hub: "desktop", vtd: "video" },
    purpose: "Confirm who the customer is and ask for recording consent. The TD consent comes later, at the car.",
    source: {
      trigger: "Receptionist opens the visit after the welcome",
      data: {
        booked: ["OMS order and CDP profile, prefilled", "User auth: OTP to the booked mobile", "Docs: DL uploaded before the visit"],
        walkin: ["Typed at the desk", "User auth: OTP", "DL scan (OCR), home-country DL if needed", "How they heard of us: source attribution"],
        vtd: ["OMS order, prefilled", "OTP read out on the call"],
      },
    },
    entry: { booked: ["Arrival logged", "Customer at the desk"], walkin: ["Walk-in visit started"], vtd: ["Customer in the call"] },
    exits: {
      hub: [
        { when: "OTP verified, valid DL on file, recording consent answered", to: "S2", state: "CHECKED IN" },
        { when: "No valid DL: car finding allowed, drive blocked", to: "S2", state: "CHECKED IN" },
        { when: "OTP fails 3 times: receptionist checks Emirates ID", to: "S2" },
      ],
      vtd: [{ when: "OTP verified on the call, recording consent answered", to: "T2", state: "VTD CHECKED IN" }],
    },
    state: { hub: "CHECKED IN", vtd: "VTD CHECKED IN" },
    screen: { name: "Test Drive detail &rsaquo; Sign-in &rsaquo; Check-in", build: "extend",
      pattern: "Journey stage Sign-in, step Check-in: DYNAMIC_FORM + OTP widget",
      route: { booked: "/test-drives/BK-88213?stage=sign-in&step=check-in", walkin: "/test-drives/VS-2041?stage=sign-in&step=check-in", vtd: "/test-drives/BK-88190?stage=video&step=check-in" } },
    dap: "POST /customer-check-in creates the work order. There is no recording consent in DAP.",
    changed: "TD consent removed from check-in. It now happens after TD start (O4).",
  },
  { id: "S2", phase: "S", name: "Assign DA", tracks: ["booked", "walkin"],
    owner: "Receptionist", device: "desktop",
    purpose: "Hand the customer to one DA who owns them from car finding to the close.",
    source: { trigger: "Check-in complete",
      data: { booked: ["Pre-assigned DA from P3", "DA roster and live status", "Daily TD capacity per DA"], walkin: ["DA roster and live status", "Daily TD capacity per DA", "Language and BI ranking"] } },
    entry: ["CHECKED IN"],
    exits: [
      { when: "DA confirmed, push sent, visit on top of the DA's queue", to: "T1", state: "DA ASSIGNED" },
      { when: "No DA free within 10 min: manager alerted", to: "M1" },
    ],
    state: "DA ASSIGNED",
    screen: { name: "Assign DA modal", build: "reuse",
      pattern: "ManualAssignmentModal + assign-direct, with a daily capacity rule", route: { booked: "/test-drives/BK-88213?stage=sign-in&step=assign-da", walkin: "/test-drives/VS-2041?stage=sign-in&step=assign-da" } },
    dap: "Manual assignment with BI-advisory ranking. Nothing blocks a DA who is at capacity.",
    changed: "Moved here from Tailor, so a DA exists before the handshake.",
  },

  // ============================== T · Tailor (handshake, then car finding)
  { id: "T1", phase: "T", name: "Handshake", tracks: ["booked", "walkin"],
    owner: "DA", device: "tablet",
    purpose: "The DA meets the customer at the desk, introduces themself and takes over. Car finding starts here.",
    source: { trigger: "DA ASSIGNED push on the DA's tablet",
      data: ["Visit context: booking, DL status, language, recording on", "CDP: cars viewed, call-centre notes"] },
    entry: ["DA ASSIGNED", "DA status is Available"],
    exits: [
      { when: "DA taps Met customer", to: "T2", state: "MET CUSTOMER" },
      { when: "Not met within 5 min: receptionist and manager alerted", to: "S2" },
    ],
    state: "MET CUSTOMER",
    screen: { name: "Test Drives &rsaquo; My queue (DA)", build: "extend",
      pattern: "DA's My queue with a waiting card and a Met customer action", route: "/test-drives?view=my-queue" },
    dap: "Hub work orders already have MET_CUSTOMER (ASSIGNED, then MET_CUSTOMER).",
    changed: "New. The DA owns the customer from here, before any car is chosen.",
  },
  { id: "T2", phase: "T", name: "Needs", tracks: ["booked", "walkin", "vtd"],
    owner: { hub: "DA", vtd: "VTD operator" }, device: { hub: "tablet", vtd: "video" },
    purpose: "Understand what the customer needs before showing any car.",
    source: { trigger: "Handshake done",
      data: { booked: ["Prefilled from the booked car and app browsing (CDP)"], walkin: ["Asked in conversation. Nothing to prefill"], vtd: ["Prefilled from the booked car (CDP)"] } },
    entry: { hub: ["MET CUSTOMER"], vtd: ["VTD CHECKED IN"] },
    exits: {
      all: [{ when: "At least budget and body type captured", to: "T3" }],
      booked: [{ when: "At least budget and body type captured", to: "T3" }, { when: "Set on the booked car: skip to the promise", to: "T4" }],
    },
    state: null,
    screen: { name: "Car finding &rsaquo; Needs", build: "new",
      pattern: "Journey stage Car finding, step Needs: DYNAMIC_FORM with chips", route: { booked: "/test-drives/BK-88213?stage=car-finding&step=needs", walkin: "/test-drives/VS-2041?stage=car-finding&step=needs", vtd: "/test-drives/BK-88190?stage=video&step=needs" } },
    dap: "No needs capture in DAP. A walk-in's car is picked at the desk.",
    changed: { all: "Now run by the DA after the handshake.", booked: "Booked customers get car finding too, starting from their booking." },
  },
  { id: "T3", phase: "T", name: "Recommend and compare", tracks: ["booked", "walkin", "vtd"],
    owner: { hub: "DA", vtd: "VTD operator, sharing their screen" }, device: { hub: "tablet", vtd: "video" },
    purpose: "Show the cars that fit, side by side, from stock at this hub.",
    source: { trigger: "Needs captured",
      data: ["Listing service: live stock at this hub, not reserved", "Recommendation model (BI)", "CDP: cars viewed"] },
    entry: ["Needs captured, or the booked car is known"],
    exits: [
      { when: "One or more cars chosen to drive", to: "T4" },
      { when: "Nothing fits today: shortlist shared", to: "N4", state: "FOLLOW-UP SCHEDULED" },
    ],
    state: null,
    screen: { name: "Car finding &rsaquo; Cars", build: "extend",
      pattern: "Test Drive Console car cards and compare modal, plus match reasons", route: { booked: "/test-drives/BK-88213?stage=car-finding&step=cars", walkin: "/test-drives/VS-2041?stage=car-finding&step=cars", vtd: "/test-drives/BK-88190?stage=video&step=cars" } },
    dap: "DAP's compare-car tool, used at the desk.",
    changed: { all: "Now run by the DA after the handshake.", booked: "The booked car is pinned, with live alternatives next to it." },
  },
  { id: "T4", phase: "T", name: "Quality promise", tracks: ["booked", "walkin", "vtd"],
    owner: { hub: "DA, tablet turned to the customer", vtd: "VTD operator, sharing their screen" }, device: { hub: "customer", vtd: "video" },
    purpose: "Give the customer reasons to trust this car before the drive.",
    source: { trigger: "Car chosen", data: ["Inspection report of the chosen car", "Warranty and return policy settings", "Finance calculator"] },
    entry: ["At least one car chosen"],
    exits: [
      { when: { hub: "Customer wants to drive today", vtd: "Customer wants to see the car on video now" }, to: "T5" },
      { when: "Wants to think: shortlist shared", to: "N4", state: "FOLLOW-UP SCHEDULED" },
    ],
    state: null,
    screen: { name: "Car finding &rsaquo; Promise (customer view)", build: "new",
      pattern: "CMS page in customer mode: LINE_TITLE + info cards", route: { booked: "/test-drives/BK-88213?stage=car-finding&step=promise", walkin: "/test-drives/VS-2041?stage=car-finding&step=promise", vtd: "/test-drives/BK-88190?stage=video&step=promise" } },
  },
  { id: "T5", phase: "T", name: "Confirm cars", tracks: ["booked", "walkin", "vtd"],
    owner: { hub: "DA", vtd: "VTD operator" }, device: { hub: "tablet", vtd: "video" },
    purpose: { walkin: "Create the order and get the cars ready for today.", booked: "Lock today's cars and get them ready.", vtd: "Confirm which car goes on camera." },
    source: { trigger: { hub: "Customer agrees to drive today", vtd: "Customer picks the car to see" },
      data: { walkin: ["OMS: create the order (car + customer)", "Prep tasks: bring the car to a bay", "Listing: hold the car for the TD window"], booked: ["OMS: keep or swap the booked car, add a second TD", "Prep tasks: bring the cars to a bay", "Listing: hold the cars"], vtd: ["OMS order", "Yard helper task: car on camera"] } },
    entry: { hub: ["Car chosen", "Customer wants to drive today", "Valid DL on file"], vtd: ["Car chosen"] },
    exits: {
      walkin: [{ when: "Order created, prep raised", to: "O1", state: "ORDER BOOKED" }, { when: "No valid DL: book a drive for later", to: "N6" }, { when: "Car is in another TD", to: "T3" }],
      booked: [{ when: "Cars confirmed, prep raised", to: "O1" }, { when: "Car is in another TD", to: "T3" }],
      vtd: [{ when: "Car confirmed, helper has it on camera", to: "O2" }],
    },
    state: { walkin: "ORDER BOOKED", booked: null, vtd: null },
    screen: { name: "Car finding &rsaquo; Confirm", build: { walkin: "new", booked: "extend", vtd: "extend" },
      pattern: { walkin: "Journey step with order summary; reuses booking-initiate and booking-confirm", booked: "Journey step with today's drive list", vtd: "Journey step with the car on camera" },
      route: { booked: "/test-drives/BK-88213?stage=car-finding&step=confirm", walkin: "/test-drives/VS-2041?stage=car-finding&step=confirm", vtd: "/test-drives/BK-88190?stage=video&step=confirm" } },
    dap: { walkin: "booking-initiate, then booking-confirm on OMS, done by the receptionist before check-in.", booked: "The booked car is fixed. A second car means a new booking.", vtd: null },
  },

  // ============================== O · On the road
  { id: "O1", phase: "O", name: "Walk to the car", tracks: ["booked", "walkin"],
    owner: "DA", device: "tablet",
    purpose: "Arrive at a car that is ready, with the customer.",
    source: { trigger: "Cars confirmed, prep raised", data: ["Prep task: car ready at a bay, keys at the bay", "Yard bay map"] },
    entry: ["Prep task done: car ready at the bay"],
    exits: [{ when: "DA and customer at the car", to: "O2" }, { when: "Car not ready in 10 min: swap the car", to: "T3" }],
    state: null,
    screen: { name: "Test drive &rsaquo; Walk to the car", build: "new",
      pattern: "Journey stage Test drive, step Walk: prep status card", route: { booked: "/test-drives/BK-88213?stage=test-drive&step=walk", walkin: "/test-drives/BK-89004?stage=test-drive&step=walk" } },
  },
  { id: "O2", phase: "O", name: "Walkaround", tracks: ["booked", "walkin", "vtd"],
    owner: { hub: "DA", vtd: "VTD operator, with a yard helper on camera" }, device: { hub: "tablet", vtd: "video" },
    purpose: { hub: "Show the car zone by zone before anyone drives.", vtd: "Walk the customer round the car on video, then play a drive clip." },
    source: { trigger: { hub: "At the car", vtd: "Car on camera" }, data: ["Inspection report", "Car features (Listing)", "Co-pilot talking points"] },
    entry: { hub: ["At the car"], vtd: ["Car on camera"] },
    exits: {
      hub: [{ when: "Zones covered", to: "O3" }, { when: "Customer goes off the car: try another", to: "T3" }],
      vtd: [{ when: "Walkaround and drive clip done", to: "O6" }],
    },
    state: null,
    screen: { name: { hub: "Test drive &rsaquo; Walkaround", vtd: "VTD console &rsaquo; Live walkaround" }, build: "new",
      pattern: { hub: "Zone checklist with talking points", vtd: "Video panel (IFRAME_RENDERER) + zone checklist" },
      route: { booked: "/test-drives/BK-88213?stage=test-drive&step=walkaround", walkin: "/test-drives/BK-89004?stage=test-drive&step=walkaround", vtd: "/test-drives/BK-88190?stage=video&step=walkaround" } },
  },
  { id: "O3", phase: "O", name: "Start TD", tracks: ["booked", "walkin"],
    owner: "DA", device: "tablet",
    purpose: "Create the TD record: car, plate, odometer and time. The consent needs this record.",
    source: { trigger: "Walkaround done, customer wants to drive", data: ["Test-drive service: START_TEST_DRIVE", "Odometer and fuel, entered by the DA"] },
    entry: ["Walkaround done", "Valid DL on file", "Car not in another active TD"],
    exits: [{ when: "TD record created", to: "O4", state: "TD STARTED" }],
    state: "TD STARTED",
    screen: { name: "Test drive &rsaquo; Start", build: "extend",
      pattern: "Journey step with the start form", route: { booked: "/test-drives/BK-88213?stage=test-drive&step=start", walkin: "/test-drives/BK-89004?stage=test-drive&step=start" } },
    dap: "Start Test Drive sends START_TEST_DRIVE.",
  },
  { id: "O4", phase: "O", name: "TD consent sign-off", tracks: ["booked", "walkin"],
    owner: "Customer, with the DA", device: "customer",
    purpose: "The customer signs the TD consent for this car before it moves.",
    source: { trigger: "TD STARTED", data: ["TD record from O3: car, plate, start time, odometer", "DL from check-in", "E-sign: signature pad, signed PDF saved to Docs"] },
    entry: ["TD STARTED", "Customer at the car"],
    exits: [
      { when: "Signed: the drive is unlocked", to: "O5", state: "TD CONSENT SIGNED" },
      { when: "Customer refuses: TD cancelled, reason logged", to: "N1" },
    ],
    state: "TD CONSENT SIGNED",
    screen: { name: "Test drive &rsaquo; Consent (customer view)", build: "new",
      pattern: "IFRAME_RENDERER e-sign micro-app (documentQcIframeBridge is the precedent)", route: { booked: "/test-drives/BK-88213?stage=test-drive&step=consent", walkin: "/test-drives/BK-89004?stage=test-drive&step=consent" } },
    dap: "The declaration e-sign unlocks after Start Test Drive but is only enforced at Mark Test Drive Complete, so today a customer can drive before signing. Here it gates the drive. VTD needs none.",
    changed: "Moved here from check-in. One consent per car, signed right after TD start.",
  },
  { id: "O5", phase: "O", name: "Drive", tracks: ["booked", "walkin"],
    owner: "DA", device: "tablet",
    purpose: "Let the car sell itself while the DA answers questions.",
    source: { trigger: "Consent signed", data: ["AI context engine: live notes", "Co-pilot: feature prompts for this car", "One-tap objection tags"] },
    entry: ["TD CONSENT SIGNED"],
    exits: [{ when: "Back at the hub", to: "O6" }],
    state: null,
    screen: { name: "Test drive &rsaquo; On the drive", build: "new",
      pattern: "Journey step with timer, prompts and objection tags", route: { booked: "/test-drives/BK-88213?stage=test-drive&step=drive", walkin: "/test-drives/BK-89004?stage=test-drive&step=drive" } },
  },
  { id: "O6", phase: "O", name: "End TD", tracks: ["booked", "walkin", "vtd"],
    owner: { hub: "DA", vtd: "VTD operator" }, device: { hub: "tablet", vtd: "video" },
    purpose: { hub: "Close the drive, then another car or the debrief.", vtd: "Close the video session." },
    source: { trigger: { hub: "Car back at the hub", vtd: "Walkaround done" }, data: { hub: ["Test-drive service: end time and odometer", "Customer's quick reaction"], vtd: ["Video provider: session end", "Customer's quick reaction"] } },
    entry: { hub: ["TD STARTED, consent signed", "Car back at the hub"], vtd: ["Video walkaround done"] },
    exits: {
      booked: [{ when: "Another car is queued: new walkaround, start and consent", to: "O1", state: "TD CONDUCTED" }, { when: "Done driving", to: "N1", state: "TD CONDUCTED" }],
      walkin: [{ when: "Another car is queued: new walkaround, start and consent", to: "O1", state: "TD CONDUCTED" }, { when: "Done driving", to: "N1", state: "TD CONDUCTED" }],
      vtd: [{ when: "Call wrapped up", to: "N1", state: "VTD CONDUCTED" }],
    },
    state: { hub: "TD CONDUCTED", vtd: "VTD CONDUCTED" },
    screen: { name: "Test drive &rsaquo; End", build: "extend",
      pattern: "Journey step; maps to Mark Test Drive Complete", route: { booked: "/test-drives/BK-88213?stage=test-drive&step=end", walkin: "/test-drives/BK-89004?stage=test-drive&step=end", vtd: "/test-drives/BK-88190?stage=video&step=end" } },
    dap: { hub: "Mark Test Drive Complete sends COMPLETE_TEST_DRIVE with the checkout form.", vtd: "A VTD is complete once its slot is marked COMPLETED." },
  },

  // ============================== N · Next step
  { id: "N1", phase: "N", name: "Debrief and decision", tracks: ["booked", "walkin", "vtd"],
    owner: { hub: "DA", vtd: "VTD operator" }, device: { hub: "tablet", vtd: "video" },
    purpose: "Agree what happens next. No visit ends without a next step.",
    source: { trigger: { hub: "TD CONDUCTED, or a visit with no drive", vtd: "VTD CONDUCTED" },
      data: ["AI context engine: summary since check-in", "Objection tags from the drive", "Finance pre-check: salary, existing EMI"] },
    entry: { hub: ["TD CONDUCTED, consent refused, or no drive today"], vtd: ["VTD CONDUCTED"] },
    exits: [
      { when: "Ready to buy", to: "N2" },
      { when: "Needs time", to: "N4", state: "FOLLOW-UP SCHEDULED" },
      { when: { hub: "Wants another car", vtd: "Wants to drive it at a hub" }, to: "N6", state: "NEW TD BOOKED" },
      { when: "Not interested", to: "N7", state: "DROPPED" },
    ],
    state: null,
    screen: { name: "Next step &rsaquo; Debrief", build: "extend",
      pattern: "DYNAMIC_FORM prefilled by the co-pilot in the CarGPT panel", route: { booked: "/test-drives/BK-88213?stage=next-step&step=debrief", walkin: "/test-drives/BK-89004?stage=next-step&step=debrief", vtd: "/test-drives/BK-88190?stage=next-step&step=debrief" } },
    dap: "The checkout form (payment mode, salary, EMI) and the checkout popup with a drop-off category.",
  },
  { id: "N2", phase: "N", name: "Collect token", tracks: ["booked", "walkin", "vtd"],
    owner: { hub: "DA", vtd: "VTD operator" }, device: { hub: "tablet", vtd: "video" },
    purpose: { hub: "Take the token while the customer is still here.", vtd: "Send a payment link while the customer is still on the call." },
    source: { trigger: "Decision: ready to buy", data: ["Payment service: Noon, DAPI, CBD UAE", "OMS: token amount for this order", "Notification engine: payment link"] },
    entry: ["Ready to buy", "Car still available"],
    exits: [
      { when: "Gateway confirms the payment", to: "N3", state: "TOKEN PAID" },
      { when: "Customer leaves before paying: link stays live, follow-up set", to: "N4" },
    ],
    state: "TOKEN PAID",
    screen: { name: "Next step &rsaquo; Token", build: "new",
      pattern: "QR, bank transfer or payment link. Status comes from the gateway, with no manual Mark as paid", route: { booked: "/test-drives/BK-88213?stage=next-step&step=token", walkin: "/test-drives/BK-89004?stage=next-step&step=token", vtd: "/test-drives/BK-88190?stage=next-step&step=token" } },
    dap: "Read-only. The customer pays in the consumer app and DAP shows TOKEN_PAYMENT_SUCCESS.",
  },
  { id: "N3", phase: "N", name: "Handoff to delivery", tracks: ["booked", "walkin", "vtd"],
    owner: "System, then RM", device: { hub: "tablet", vtd: "video" },
    purpose: "Start the delivery journey with nothing lost.",
    source: { trigger: "TOKEN PAID", data: ["Delivery service: documents, finance, VAS, agreement, registration, delivery", "Leadverse Order personas"] },
    entry: ["TOKEN PAID"],
    exits: [{ when: "Delivery tasks created, RM assigned. The TD journey closes", to: null, state: "CONVERTED" }],
    state: null,
    screen: { name: "Next step &rsaquo; Handoff", build: "reuse",
      pattern: "Existing Order personas: Delivery Schedule, FinOps, VAS Refurb, RM", route: { booked: "/test-drives/BK-88213?stage=next-step&step=handoff", walkin: "/test-drives/BK-89004?stage=next-step&step=handoff", vtd: "/test-drives/BK-88190?stage=next-step&step=handoff" } },
  },
  { id: "N4", phase: "N", name: "Schedule follow-up", tracks: ["booked", "walkin", "vtd"], branch: true,
    owner: { hub: "DA", vtd: "VTD operator" }, device: { hub: "tablet", vtd: "video" },
    purpose: "Agree a date and send the shortlist before the customer leaves.",
    source: { trigger: "Needs time, nothing fits today, or payment pending", data: ["Shortlist from T3", "RM calendar"] },
    entry: ["Needs time, nothing fits, or payment pending"],
    exits: [{ when: "Date agreed, shortlist sent, RM task created", to: "N5", state: "FOLLOW-UP SCHEDULED" }],
    state: "FOLLOW-UP SCHEDULED",
    screen: { name: "Next step &rsaquo; Follow-up", build: "extend",
      pattern: "Journey step that creates a Tasks entry for the RM", route: { booked: "/test-drives/BK-88213?stage=next-step&step=follow-up", walkin: "/test-drives/BK-89004?stage=next-step&step=follow-up", vtd: "/test-drives/BK-88190?stage=next-step&step=follow-up" } },
  },
  { id: "N5", phase: "N", name: "Follow-up call", tracks: ["booked", "walkin", "vtd"], branch: true,
    owner: "RM", device: "desktop",
    purpose: "Call on the agreed date and move the customer forward.",
    source: { trigger: "Follow-up date reached", data: ["Tasks: TD follow-up persona", "Visit summary from the co-pilot", "Listing: shortlist availability and price changes"] },
    entry: ["FOLLOW-UP SCHEDULED date reached"],
    exits: [
      { when: "Ready to buy: send a payment link", to: "N2" },
      { when: "Wants another drive", to: "N6" },
      { when: "No answer after 3 attempts, or not interested", to: "N7", state: "DROPPED" },
    ],
    state: null,
    screen: { name: "Tasks &rsaquo; TD follow-up", build: "reuse",
      pattern: "Tasks &rarr; Lead &rarr; TD follow-up persona", route: "/tasks/TK-5012" },
  },
  { id: "N6", phase: "N", name: "Book another TD", tracks: ["booked", "walkin", "vtd"], branch: true,
    owner: { hub: "DA or RM", vtd: "VTD operator" }, device: { hub: "tablet", vtd: "video" },
    purpose: { hub: "Book the next drive before the customer leaves.", vtd: "Turn the video viewing into a hub test drive." },
    source: { trigger: { hub: "Wants another car, or no valid DL today", vtd: "Wants to drive the car" }, data: ["Slot capacity", "OMS"] },
    entry: ["Decision: another car, or a hub TD"],
    exits: [{ when: "Slot confirmed", to: "P3", state: "NEW TD BOOKED" }],
    state: "NEW TD BOOKED",
    screen: { name: "Book test drive &rsaquo; Slot picker", build: "reuse",
      pattern: "The same slot picker as P2", route: { booked: "/test-drives/BK-88213?panel=book-td", walkin: "/test-drives/BK-89004?panel=book-td", vtd: "/test-drives/BK-88190?panel=book-td" } },
  },
  { id: "N7", phase: "N", name: "Close as dropped", tracks: ["booked", "walkin", "vtd"], branch: true,
    owner: "DA or RM", device: { hub: "tablet", vtd: "video" },
    purpose: "Record why the customer said no.",
    source: { trigger: "Not interested, or follow-up attempts used up", data: ["Drop reasons from CRUISE: mechanical, non-mechanical, pricing, assortment"] },
    entry: ["Not interested, or 3 follow-up attempts used"],
    exits: [{ when: "Reason saved", to: null, state: "DROPPED" }],
    state: "DROPPED",
    screen: { name: "Next step &rsaquo; Close", build: "extend",
      pattern: "Journey step with reason and sub-reason", route: { booked: "/test-drives/BK-88213?stage=next-step&step=close", walkin: "/test-drives/BK-89004?stage=next-step&step=close", vtd: "/test-drives/BK-88190?stage=next-step&step=close" } },
    dap: "The checkout popup asks for a drop-off category from a config list.",
  },

  // ============================== M · Oversight
  { id: "M1", phase: "M", name: "Live funnel", tracks: ["booked", "walkin", "vtd"],
    owner: "Manager (DATL)", device: "desktop",
    purpose: "See every visit by state, and step in when a step runs late.",
    source: { trigger: "Always on", data: ["Every state on this page, with timestamps"] },
    entry: ["Manager role"],
    exits: [{ when: "Customer waiting more than 5 min for a DA: reassign", to: "S2" }],
    state: null,
    screen: { name: "Manager Oversight &rsaquo; TD funnel", build: "extend",
      pattern: "Manager Oversight + a funnel widget over the same state events", route: "/test-drives/oversight?view=funnel" },
  },
];

function stepById(id) { return STEPS.find(s => s.id === id); }
function stepsForTrack(track) { return STEPS.filter(s => s.tracks.includes(track)); }
function phaseById(id) { return PHASES.find(p => p.id === id); }

// ---------------------------------------------------------------- mock entities for the screens
const PCARS = {
  c1: { id: "c1", title: "2023 Nissan Altima SV", price: 62900, km: "18,400 km", body: "Sedan", drive: "2WD", fuel: "Petrol", trans: "Automatic", seats: 5, color: "#DCE3EA", url: "https://www.cars24.ae/buy-used-nissan-altima-cars-dubai/", plate: "Dubai P 48213", bay: "Bay 2" },
  c2: { id: "c2", title: "2022 Toyota Camry GLE", price: 71500, km: "24,100 km", body: "Sedan", drive: "2WD", fuel: "Petrol", trans: "Automatic", seats: 5, color: "#E5DED0", url: "https://www.cars24.ae/buy-used-toyota-camry-cars-dubai/", plate: "Dubai K 30190", bay: "Studio 1" },
  c3: { id: "c3", title: "2023 Hyundai Tucson", price: 68200, km: "12,900 km", body: "SUV", drive: "4WD", fuel: "Petrol", trans: "Automatic", seats: 5, color: "#D9E2DC", url: "https://www.cars24.ae/buy-used-hyundai-tucson-cars-dubai/", plate: "Dubai R 77105", bay: "Bay 4" },
  c4: { id: "c4", title: "2022 Kia Sportage", price: 59900, km: "31,200 km", body: "SUV", drive: "2WD", fuel: "Petrol", trans: "Automatic", seats: 5, color: "#E6D9D9", url: "https://www.cars24.ae/buy-used-kia-sportage-cars-dubai/", plate: "Dubai M 21877", bay: "Bay 1" },
};

const PEOPLE = {
  booked: { name: "Fatima Al Suwaidi", phone: "050 123 4567", email: "fatima.s@example.com", id: "BK-88213", visit: "BK-88213", nationality: "UAE", language: "Arabic", dl: "DXB-882134", source: "Consumer app", slot: "Today, 2:30 PM", car: "c1",
    needs: { budget: "AED 55k&ndash;70k", body: ["Sedan", "SUV"], fuel: "Petrol", trans: "Automatic", drive: "2WD", usage: ["City", "Family weekends"], must: ["Apple CarPlay"] },
    picks: [["c1", 94, "Booked car &middot; in budget &middot; CarPlay"], ["c3", 88, "SUV, more boot space &middot; in budget"], ["c2", 81, "Sedan &middot; AED 1,500 over budget"]] },
  walkin: { name: "Ahmed Saleh", phone: "058 330 4471", email: "ahmed.saleh@example.com", id: "BK-89004", visit: "VS-2041", nationality: "Egypt", language: "Arabic, English", dl: "DXB-1190245", homeDl: "EG-55120988 (Egypt)", source: "Drive-by", car: "c4",
    needs: { budget: "AED 55k&ndash;65k", body: ["SUV"], fuel: "Petrol", trans: "Automatic", drive: "2WD", usage: ["Family", "Long drives"], must: ["7 airbags", "Rear camera"] },
    picks: [["c4", 92, "SUV &middot; in budget &middot; rear camera"], ["c3", 86, "SUV, 4WD &middot; AED 3,200 over budget"], ["c1", 70, "Sedan &middot; in budget"]] },
  vtd: { name: "Khalid Al Jaberi", phone: "055 987 1230", email: "khalid.j@example.com", id: "BK-88190", visit: "BK-88190", nationality: "UAE", language: "English", dl: "AUH-190552", source: "Chatbot", slot: "Today, 3:00 PM", car: "c2",
    needs: { budget: "AED 65k&ndash;75k", body: ["Sedan"], fuel: "Petrol", trans: "Automatic", drive: "2WD", usage: ["Commute to Dubai"], must: ["Adaptive cruise"] },
    picks: [["c2", 93, "Booked car &middot; adaptive cruise"], ["c1", 84, "Sedan &middot; AED 8,600 cheaper"]] },
};

const PSTAFF = {
  receptionist: { name: "Kishor", init: "K", role: "RECEPTIONIST" },
  da: { name: "Omar Hassan", init: "OH", role: "COMMON_DA" },
  operator: { name: "Sara Ibrahim", init: "SI", role: "VIRTUAL_DA" },
  manager: { name: "Aaliya Patel", init: "AP", role: "DATL" },
  cc: { name: "Reem Khalifa", init: "RK", role: "Call centre" },
  rm: { name: "Rania Haddad", init: "RH", role: "RM" },
  prep: { name: "Bilal Raza", init: "BR", role: "PREP_USER" },
};

const PDAS = [
  { id: "da1", name: "Omar Hassan", role: "COMMON_DA", lang: "Arabic, English", status: "AVAILABLE", today: 6, max: 10, score: 92, pre: true },
  { id: "da2", name: "Layla Ahmed", role: "HUB_DA", lang: "English, Hindi", status: "AVAILABLE", today: 3, max: 10, score: 88 },
  { id: "da5", name: "Faisal Noor", role: "HUB_DA", lang: "Arabic, Urdu", status: "ON_BREAK", today: 5, max: 10, score: 84 },
  { id: "da4", name: "Yusuf Khan", role: "HOME_DA", lang: "English", status: "AVAILABLE", today: 10, max: 10, score: 75 },
];

function aed(n) { return "AED " + n.toLocaleString("en-US"); }
function inits(name) { return (name || "?").trim().split(/\s+/).map(w => w[0]).slice(0, 2).join("").toUpperCase(); }
